//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteMercado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class avaliacao_usuario_empresa_cotada
    {
        public int ID_AVALIACAO_USUARIO_EMPRESA_COTADA { get; set; }
        public int ID_CODIGO_EMPRESA_USUARIO { get; set; }
        public int ID_CODIGO_COTACAO_MASTER { get; set; }
        public int ID_CODIGO_CLASSIFICACAO_USUARIO { get; set; }
        public System.DateTime DATA_AVALIACAO_USUARIO_EMPRESA_COTADA { get; set; }
        public int ID_CODIGO_EMPRESA_USUARIO_AVALIOU { get; set; }
    
        public virtual empresa_usuario empresa_usuario { get; set; }
        public virtual cotacao_master cotacao_master { get; set; }
        public virtual classificacao_usuario_empresa_cotada classificacao_usuario_empresa_cotada { get; set; }
    }
}
