//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteMercado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chat_cotacao
    {
        public int ID_CODIGO_CHAT_COTACAO { get; set; }
        public int ID_CODIGO_COTACAO_FILHA { get; set; }
        public System.DateTime DATA_CHAT_COTACAO { get; set; }
        public System.TimeSpan HORA_CHAT_COTACAO { get; set; }
        public int ID_CODIGO_EMPRESA_USUARIO_COTANTE_COTADA { get; set; }
        public string TEXTO_CHAT_COTACAO { get; set; }
        public int ORDEM_EXIBICAO_CHAT_COTACAO { get; set; }
    
        public virtual cotacao_filha cotacao_filha { get; set; }
        public virtual empresa_usuario empresa_usuario { get; set; }
    }
}
