//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteMercado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cidades_empresa_usuario
    {
        public cidades_empresa_usuario()
        {
            this.bairros_empresa_usuario = new HashSet<bairros_empresa_usuario>();
        }
    
        public int ID_CODIGO_CIDADE_EMPRESA_USUARIO { get; set; }
        public string ID_UF { get; set; }
        public string NOME_CIDADE_EMPRESA_USUARIO { get; set; }
    
        public virtual ICollection<bairros_empresa_usuario> bairros_empresa_usuario { get; set; }
        public virtual estados_empresa_usuario estados_empresa_usuario { get; set; }
    }
}
