//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteMercado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class classificacao_empresa_cotada
    {
        public classificacao_empresa_cotada()
        {
            this.avaliacao_empresa_cotada = new HashSet<avaliacao_empresa_cotada>();
        }
    
        public int ID_CODIGO_CLASSIFICACAO_EMPRESA { get; set; }
        public string DESCRICAO_CLASSIFICACAO_EMPRESA { get; set; }
        public int PONTUACAO_CLASSIFICACAO_EMPRESA { get; set; }
        public bool CLASSIFICACAO_ATIVA { get; set; }
        public System.DateTime DATA_CADASTRO_CLASSIFICACAO_EMPRESA { get; set; }
        public Nullable<System.DateTime> DATA_INATIVOU_CLASSIFICACAO_EMPRESA { get; set; }
        public Nullable<int> ID_CODIGO_EMPRESA_USUARIO_INATIVOU_CLASSIFICACAO_EMPRESA { get; set; }
    
        public virtual ICollection<avaliacao_empresa_cotada> avaliacao_empresa_cotada { get; set; }
    }
}
