//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteMercado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cotacao_filha
    {
        public cotacao_filha()
        {
            this.chat_cotacao = new HashSet<chat_cotacao>();
            this.cotacao_negociacao = new HashSet<cotacao_negociacao>();
            this.pedidoes = new HashSet<pedido>();
        }
    
        public int ID_CODIGO_COTACAO_FILHA { get; set; }
        public int ID_CODIGO_COTACAO_MASTER { get; set; }
        public int ID_CODIGO_EMPRESA_USUARIO_EMPRESA_COTADA { get; set; }
        public int ID_CODIGO_EMPRESA_USUARIO_USUARIO_COTADA { get; set; }
        public System.DateTime DATA_RESPOSTA_COTACAO_FILHA { get; set; }
        public bool RESPONDIDA_COTACAO_FILHA { get; set; }
        public Nullable<int> PRECO_LOTE_ITENS_COTACAO { get; set; }
    
        public virtual ICollection<chat_cotacao> chat_cotacao { get; set; }
        public virtual cotacao_master cotacao_master { get; set; }
        public virtual empresa_usuario empresa_usuario { get; set; }
        public virtual empresa_usuario empresa_usuario1 { get; set; }
        public virtual ICollection<cotacao_negociacao> cotacao_negociacao { get; set; }
        public virtual ICollection<pedido> pedidoes { get; set; }
    }
}
