//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteMercado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cotacao_negociacao
    {
        public cotacao_negociacao()
        {
            this.itens_pedido = new HashSet<itens_pedido>();
        }
    
        public int ID_CODIGO_COTACAO_NEGOCIACAO { get; set; }
        public int ID_CODIGO_COTACAO_FILHA { get; set; }
        public int ID_CODIGO_ITENS_COTACAO { get; set; }
        public string DESCRICAO_PRODUTO_EDITADO_COTADA { get; set; }
        public int PRECO_ITENS_COTACAO { get; set; }
        public int QUANTIDADE_ITENS_COTACAO { get; set; }
        public int ID_CODIGO_TIPO_RESPOSTA_COTACAO { get; set; }
        public bool PRODUTO_COTADO { get; set; }
    
        public virtual cotacao_filha cotacao_filha { get; set; }
        public virtual itens_cotacao itens_cotacao { get; set; }
        public virtual tipo_resposta_cotacao tipo_resposta_cotacao { get; set; }
        public virtual ICollection<itens_pedido> itens_pedido { get; set; }
    }
}
