//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteMercado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cotacao_master
    {
        public cotacao_master()
        {
            this.avaliacao_empresa_cotada = new HashSet<avaliacao_empresa_cotada>();
            this.avaliacao_usuario_empresa_cotada = new HashSet<avaliacao_usuario_empresa_cotada>();
            this.cotacao_filha = new HashSet<cotacao_filha>();
            this.itens_cotacao = new HashSet<itens_cotacao>();
            this.pedidoes = new HashSet<pedido>();
        }
    
        public int ID_CODIGO_COTACAO_MASTER { get; set; }
        public int ID_CODIGO_EMPRESA_USUARIO_EMPRESA_COTANTE { get; set; }
        public int ID_CODIGO_EMPRESA_USUARIO_USUARIO_COTANTE { get; set; }
        public string NOME_COTACAO { get; set; }
        public System.DateTime DATA_CRIACAO_COTACAO { get; set; }
        public Nullable<int> ID_CODIGO_TIPOS_FRETE { get; set; }
        public string CONDICAO_PAGAMENTO_COTACAO { get; set; }
        public string OBSERVACAO_COTACAO { get; set; }
        public Nullable<int> PERCENTUAL_RESPONDIDA_COTACAO { get; set; }
        public Nullable<int> ID_CODIGO_STATUS_COTACAO { get; set; }
    
        public virtual ICollection<avaliacao_empresa_cotada> avaliacao_empresa_cotada { get; set; }
        public virtual ICollection<avaliacao_usuario_empresa_cotada> avaliacao_usuario_empresa_cotada { get; set; }
        public virtual ICollection<cotacao_filha> cotacao_filha { get; set; }
        public virtual empresa_usuario empresa_usuario { get; set; }
        public virtual empresa_usuario empresa_usuario1 { get; set; }
        public virtual tipos_frete tipos_frete { get; set; }
        public virtual status_cotacao status_cotacao { get; set; }
        public virtual ICollection<itens_cotacao> itens_cotacao { get; set; }
        public virtual ICollection<pedido> pedidoes { get; set; }
    }
}
