//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteMercado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_identificador_empresa_usuario
    {
        public int ID_CODIGO_DOC_IDENTIFICADOR_EMPRESA_USUARIO { get; set; }
        public int ID_CODIGO_EMPRESA_USUARIO { get; set; }
        public int ID_CODIGO_EMPRESA_USUARIO_EMPRESA { get; set; }
    
        public virtual empresa_usuario empresa_usuario { get; set; }
    }
}
