//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteMercado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class empresa_fabricante_marcas
    {
        public empresa_fabricante_marcas()
        {
            this.produtoes = new HashSet<produto>();
        }
    
        public int ID_CODIGO_EMPRESA_FABRICANTE_MARCAS { get; set; }
        public string DESCRICAO_EMPRESA_FABRICANTE_MARCAS { get; set; }
    
        public virtual ICollection<produto> produtoes { get; set; }
    }
}
