//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteMercado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class empresa_usuario
    {
        public empresa_usuario()
        {
            this.avaliacao_empresa_cotada = new HashSet<avaliacao_empresa_cotada>();
            this.avaliacao_usuario_empresa_cotada = new HashSet<avaliacao_usuario_empresa_cotada>();
            this.chat_cotacao = new HashSet<chat_cotacao>();
            this.cotacao_filha = new HashSet<cotacao_filha>();
            this.cotacao_filha1 = new HashSet<cotacao_filha>();
            this.cotacao_master = new HashSet<cotacao_master>();
            this.cotacao_master1 = new HashSet<cotacao_master>();
            this.doc_identificador_empresa_usuario = new HashSet<doc_identificador_empresa_usuario>();
            this.empresa_usuario_logins = new HashSet<empresa_usuario_logins>();
            this.enderecos_empresa_usuario = new HashSet<enderecos_empresa_usuario>();
            this.enderecos_internet = new HashSet<enderecos_internet>();
            this.financeiro_cobranca_faturamento = new HashSet<financeiro_cobranca_faturamento>();
            this.financeiro_cobranca_faturamento1 = new HashSet<financeiro_cobranca_faturamento>();
            this.profissao_usuario_empresa = new HashSet<profissao_usuario_empresa>();
            this.ramo_atividade_empresa_usuario = new HashSet<ramo_atividade_empresa_usuario>();
            this.telefones_empresa_usuario = new HashSet<telefones_empresa_usuario>();
            this.tipo_contrato_empresa_usuario_cotada = new HashSet<tipo_contrato_empresa_usuario_cotada>();
            this.usuario_historico_empresas = new HashSet<usuario_historico_empresas>();
            this.usuario_modulo = new HashSet<usuario_modulo>();
        }
    
        public int ID_CODIGO_EMPRESA_USUARIO { get; set; }
        public int ID_CODIGO_TIPO_EMPRESA_USUARIO { get; set; }
        public int ID_CODIGO_DOC_IDENTIFICADOR_EMPRESA_USUARIO { get; set; }
        public string NOME_EMPRESA_USUARIO { get; set; }
        public string NOME_FANTASIA_EMPRESA_USUARIO { get; set; }
        public string LOGOMARCA_EMPRESA_USUARIO { get; set; }
        public bool USUARIO_MASTER_EMPRESA_USUARIO { get; set; }
        public bool RECEBER_EMAILS_EMPRESA_USUARIO { get; set; }
        public System.DateTime DATA_CADASTRO_EMPRESA_USUARIO { get; set; }
        public System.DateTime DATA_ULTIMA_ATUALIZACAO_EMPRESA_USUARIO { get; set; }
        public bool ATIVA_INATIVA_EMPRESA_USUARIO { get; set; }
        public Nullable<System.DateTime> DATA_INATIVOU_EMPRESA_USUARIO { get; set; }
        public Nullable<int> ID_CODIGO_EMPRESA_USUARIO_INATIVOU { get; set; }
        public bool EMPRESA_ADM { get; set; }
    
        public virtual ICollection<avaliacao_empresa_cotada> avaliacao_empresa_cotada { get; set; }
        public virtual ICollection<avaliacao_usuario_empresa_cotada> avaliacao_usuario_empresa_cotada { get; set; }
        public virtual ICollection<chat_cotacao> chat_cotacao { get; set; }
        public virtual ICollection<cotacao_filha> cotacao_filha { get; set; }
        public virtual ICollection<cotacao_filha> cotacao_filha1 { get; set; }
        public virtual ICollection<cotacao_master> cotacao_master { get; set; }
        public virtual ICollection<cotacao_master> cotacao_master1 { get; set; }
        public virtual ICollection<doc_identificador_empresa_usuario> doc_identificador_empresa_usuario { get; set; }
        public virtual ICollection<empresa_usuario_logins> empresa_usuario_logins { get; set; }
        public virtual tipo_empresa_usuario tipo_empresa_usuario { get; set; }
        public virtual ICollection<enderecos_empresa_usuario> enderecos_empresa_usuario { get; set; }
        public virtual ICollection<enderecos_internet> enderecos_internet { get; set; }
        public virtual ICollection<financeiro_cobranca_faturamento> financeiro_cobranca_faturamento { get; set; }
        public virtual ICollection<financeiro_cobranca_faturamento> financeiro_cobranca_faturamento1 { get; set; }
        public virtual ICollection<profissao_usuario_empresa> profissao_usuario_empresa { get; set; }
        public virtual ICollection<ramo_atividade_empresa_usuario> ramo_atividade_empresa_usuario { get; set; }
        public virtual ICollection<telefones_empresa_usuario> telefones_empresa_usuario { get; set; }
        public virtual ICollection<tipo_contrato_empresa_usuario_cotada> tipo_contrato_empresa_usuario_cotada { get; set; }
        public virtual ICollection<usuario_historico_empresas> usuario_historico_empresas { get; set; }
        public virtual ICollection<usuario_modulo> usuario_modulo { get; set; }
    }
}
