//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteMercado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class enderecos_internet
    {
        public int ID_CODIGO_EMPRESA_USUARIO { get; set; }
        public string EMAIL1_EMPRESA_USUARIO { get; set; }
        public string EMAIL2_EMPRESA_USUARIO { get; set; }
        public string PAGINA_HOME_EMPRESA_USUARIO { get; set; }
        public string PAGINA_FUN_EMPRESA_USUARIO { get; set; }
    
        public virtual empresa_usuario empresa_usuario { get; set; }
    }
}
