//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteMercado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class enderecos_empresa_usuario
    {
        public int ID_CODIGO_ENDERECO_EMPRESA_USUARIO { get; set; }
        public int ID_CODIGO_EMPRESA_USUARIO { get; set; }
        public long ID_CEP_ENDERECO_EMPRESA_USUARIO { get; set; }
        public Nullable<int> ID_CEP_SEQUENCIAL_ENDERECO { get; set; }
        public int NUMERO_ENDERECO_EMPRESA_USUARIO { get; set; }
        public string COMPLEMENTO_ENDERECO_EMPRESA_USUARIO { get; set; }
        public string REFERENCIA_ENDERECO_EMPRESA_USUARIO { get; set; }
    
        public virtual empresa_usuario empresa_usuario { get; set; }
    }
}
