//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteMercado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class enderecos_cep_empresa_usuario
    {
        public long ID_CEP_ENDERECO_EMPRESA_USUARIO { get; set; }
        public int ID_CEP_SEQUENCIAL_ENDERECO { get; set; }
        public string ENDERECO_EMPRESA_USUARIO { get; set; }
        public int ID_CODIGO_BAIRRO_EMPRESA_USUARIO { get; set; }
    
        public virtual bairros_empresa_usuario bairros_empresa_usuario { get; set; }
    }
}
