//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteMercado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class estados_empresa_usuario
    {
        public estados_empresa_usuario()
        {
            this.cidades_empresa_usuario = new HashSet<cidades_empresa_usuario>();
        }
    
        public string ID_UF { get; set; }
        public string NOME_ESTADO_EMPRESA_USUARIO { get; set; }
    
        public virtual ICollection<cidades_empresa_usuario> cidades_empresa_usuario { get; set; }
    }
}
