//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteMercado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class financeiro_cobranca_faturamento
    {
        public int ID_CODIGO_COBRANCA_FATURAMENTO { get; set; }
        public int ID_CODIGO_EMPRESA_USUARIO { get; set; }
        public int ID_CODIGO_EMPRESA_USUARIO_USUARIO { get; set; }
        public int ID_TIPO_CONTRATO_EMPRESA_USUARIO_COTADA { get; set; }
        public string OBSERVACAO_BOLETO_COBRANCA_FATURAMENTO { get; set; }
        public bool PARCELA_PAGA_COBRANCA_FATURAMENTO { get; set; }
    
        public virtual empresa_usuario empresa_usuario { get; set; }
        public virtual empresa_usuario empresa_usuario1 { get; set; }
        public virtual tipo_contrato_empresa_usuario_cotada tipo_contrato_empresa_usuario_cotada { get; set; }
    }
}
