//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteMercado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class itens_cotacao
    {
        public itens_cotacao()
        {
            this.cotacao_negociacao = new HashSet<cotacao_negociacao>();
        }
    
        public int ID_CODIGO_ITENS_COTACAO { get; set; }
        public int ID_CODIGO_COTACAO_MASTER { get; set; }
        public int ID_CODIGO_PRODUTO { get; set; }
        public Nullable<int> ID_CODIGO_PEDIDO { get; set; }
        public string FOTO_TIPO_ITENS_COTACAO { get; set; }
        public Nullable<int> ID_CODIGO_TIPO_ITENS_COTACAO { get; set; }
        public int QUANTIDADE_ITENS_COTACAO { get; set; }
        public int ID_CODIGO_UNIDADE_PRODUTO { get; set; }
    
        public virtual cotacao_master cotacao_master { get; set; }
        public virtual ICollection<cotacao_negociacao> cotacao_negociacao { get; set; }
        public virtual produto produto { get; set; }
        public virtual pedido pedido { get; set; }
        public virtual tipos_item_cotacao tipos_item_cotacao { get; set; }
        public virtual unidades_produto unidades_produto { get; set; }
    }
}
