//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteMercado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class modulo
    {
        public modulo()
        {
            this.usuario_modulo = new HashSet<usuario_modulo>();
            this.usuario_modulo_historico_empresas = new HashSet<usuario_modulo_historico_empresas>();
        }
    
        public int ID_CODIGO_MODULO { get; set; }
        public string DESCRICAO_MODULO { get; set; }
        public int TEMPO_LIMITE_USO_MODULO { get; set; }
        public string CAMINHO_ACESSO_MODULO { get; set; }
        public string OBSERVACAO_MODULO { get; set; }
    
        public virtual ICollection<usuario_modulo> usuario_modulo { get; set; }
        public virtual ICollection<usuario_modulo_historico_empresas> usuario_modulo_historico_empresas { get; set; }
    }
}
