//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteMercado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedido
    {
        public pedido()
        {
            this.itens_cotacao = new HashSet<itens_cotacao>();
            this.itens_pedido = new HashSet<itens_pedido>();
        }
    
        public int ID_CODIGO_PEDIDO { get; set; }
        public int ID_CODIGO_COTACAO_MASTER { get; set; }
        public int ID_CODIGO_COTACAO_FILHA { get; set; }
        public System.DateTime DATA_PEDIDO { get; set; }
        public System.DateTime DATA_ENTREGA_PEDIDO { get; set; }
        public bool CONFIRMADO_PEDIDO { get; set; }
    
        public virtual cotacao_filha cotacao_filha { get; set; }
        public virtual cotacao_master cotacao_master { get; set; }
        public virtual ICollection<itens_cotacao> itens_cotacao { get; set; }
        public virtual ICollection<itens_pedido> itens_pedido { get; set; }
    }
}
