//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteMercado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class produto
    {
        public produto()
        {
            this.itens_cotacao = new HashSet<itens_cotacao>();
        }
    
        public int ID_CODIGO_PRODUTO { get; set; }
        public int ID_CODIGO_EMPRESA_FABRICANTE_MARCAS { get; set; }
        public string DESCRICAO_PRODUTO { get; set; }
        public int ID_CODIGO_UNIDADE_PRODUTO { get; set; }
        public Nullable<int> PRECO_PRODUTO { get; set; }
        public System.DateTime DATA_CADASTRO_PRODUTO { get; set; }
        public bool PRODUTO_ATIVO { get; set; }
        public Nullable<System.DateTime> DATA_INATIVOU_PRODUTO { get; set; }
        public Nullable<int> ID_CODIGO_EMPRESA_USUARIO_INATIVOU { get; set; }
    
        public virtual empresa_fabricante_marcas empresa_fabricante_marcas { get; set; }
        public virtual ICollection<itens_cotacao> itens_cotacao { get; set; }
        public virtual unidades_produto unidades_produto { get; set; }
    }
}
