//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteMercado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class profissoes_usuario
    {
        public profissoes_usuario()
        {
            this.profissao_usuario_empresa = new HashSet<profissao_usuario_empresa>();
        }
    
        public int ID_CODIGO_PROFISSAO { get; set; }
        public string DESCRICAO_PROFISSAO { get; set; }
    
        public virtual ICollection<profissao_usuario_empresa> profissao_usuario_empresa { get; set; }
    }
}
