//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteMercado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class profissao_usuario_empresa
    {
        public int ID_CODIGO_PROFISSAO_USUARIO_EMPRESA { get; set; }
        public int ID_CODIGO_EMPRESA_USUARIO { get; set; }
        public int ID_CODIGO_PROFISSAO { get; set; }
        public bool PROFISSAO_ATIVA_USUARIO_EMPRESA { get; set; }
        public System.DateTime DATA_CADASTRO_PROFISSAO_USUARIO_EMPRESA { get; set; }
        public Nullable<int> DATA_INATIVOU_PROFISSAO_USUARIO_EMPRESA { get; set; }
        public Nullable<int> ID_CODIGO_EMPRESA_USUARIO_INATIVOU { get; set; }
    
        public virtual empresa_usuario empresa_usuario { get; set; }
        public virtual profissoes_usuario profissoes_usuario { get; set; }
    }
}
