//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteMercado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ramo_atividade_empresa_usuario
    {
        public int ID_CODIGO_RAMO_EMPRESA_USUARIO { get; set; }
        public int ID_CODIGO_EMPRESA_USUARIO { get; set; }
        public string DESCRICAO_RAMO_EMPRESA { get; set; }
        public System.DateTime DATA_ATIVACAO_RAMO_EMPRESA { get; set; }
        public Nullable<System.DateTime> DATA_DESATIVACAO_RAMO_EMPRESA { get; set; }
        public Nullable<int> ID_CODIGO_EMPRESA_USUARIO_INATIVOU { get; set; }
    
        public virtual empresa_usuario empresa_usuario { get; set; }
    }
}
