//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteMercado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class status_cotacao
    {
        public status_cotacao()
        {
            this.cotacao_master = new HashSet<cotacao_master>();
        }
    
        public int ID_CODIGO_STATUS_COTACAO { get; set; }
        public string DESCRICAO_STATUS_COTACAO { get; set; }
        public System.DateTime DATA_INCLUSAO_STATUS_COTACAO { get; set; }
        public bool ATIVO_STATUS_COTACAO { get; set; }
        public Nullable<System.DateTime> DATA_INATIVOU_STATUS_COTACAO { get; set; }
        public Nullable<int> ID_CODIGO_EMPRESA_USUARIO_INATIVOU { get; set; }
    
        public virtual ICollection<cotacao_master> cotacao_master { get; set; }
    }
}
