//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteMercado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class telefones_empresa_usuario
    {
        public int ID_CODIGO_TELEFONES_EMPRESA_USUARIO { get; set; }
        public int ID_CODIGO_EMPRESA_USUARIO { get; set; }
        public int ID_CODIGO_TIPOS_TELEFONE_EMPRESA_USUARIO { get; set; }
        public string DDD_TELEFONE_EMPRESA_USUARIO { get; set; }
        public string TELEFONE_EMPRESA_USUARIO { get; set; }
        public string RAMAL_TELEFONE_EMPRESA_USUARIO { get; set; }
    
        public virtual empresa_usuario empresa_usuario { get; set; }
        public virtual tipos_telefone_empresa_usuario tipos_telefone_empresa_usuario { get; set; }
    }
}
