//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteMercado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipos_frete
    {
        public tipos_frete()
        {
            this.cotacao_master = new HashSet<cotacao_master>();
        }
    
        public int ID_CODIGO_TIPOS_FRETE { get; set; }
        public string DESCRICAO_TIPOS_FRETE { get; set; }
    
        public virtual ICollection<cotacao_master> cotacao_master { get; set; }
    }
}
