//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteMercado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo_resposta_cotacao
    {
        public tipo_resposta_cotacao()
        {
            this.cotacao_negociacao = new HashSet<cotacao_negociacao>();
        }
    
        public int ID_CODIGO_TIPO_RESPOSTA_COTACAO { get; set; }
        public string DESCRICAO_TIPO_RESPOSTA_COTACAO { get; set; }
    
        public virtual ICollection<cotacao_negociacao> cotacao_negociacao { get; set; }
    }
}
