//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteMercado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipos_item_cotacao
    {
        public tipos_item_cotacao()
        {
            this.itens_cotacao = new HashSet<itens_cotacao>();
        }
    
        public int ID_CODIGO_TIPO_ITENS_COTACAO { get; set; }
        public string DESCRICAO_TIPO_ITENS_COTACAO { get; set; }
    
        public virtual ICollection<itens_cotacao> itens_cotacao { get; set; }
    }
}
