//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteMercado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipos_telefone_empresa_usuario
    {
        public tipos_telefone_empresa_usuario()
        {
            this.telefones_empresa_usuario = new HashSet<telefones_empresa_usuario>();
        }
    
        public int ID_CODIGO_TIPOS_TELEFONE_EMPRESA_USUARIO { get; set; }
        public string DESCRICAO_TIPOS_TELEFONE { get; set; }
    
        public virtual ICollection<telefones_empresa_usuario> telefones_empresa_usuario { get; set; }
    }
}
