//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteMercado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipos_contrato
    {
        public tipos_contrato()
        {
            this.tipo_contrato_empresa_usuario_cotada = new HashSet<tipo_contrato_empresa_usuario_cotada>();
        }
    
        public int ID_CODIGO_TIPO_CONTRATO_COTADA { get; set; }
        public int CODIGO_REFERENCIA_TIPO_COTRATO_COTADA { get; set; }
        public string DESCRICAO_TIPO_CONTRATO_COTADA { get; set; }
        public int VALOR_MENSAL_TIPO_CONTRATO_COTADA { get; set; }
        public int DIAS_TOLERANCIA_COBRANCA_ANTES_POS_VENCIMENTO { get; set; }
        public System.DateTime DATA_CADASTRO_TIPO_CONTRATO { get; set; }
        public bool ATIVO_TIPO_CONTRATO_COTADA { get; set; }
        public Nullable<System.DateTime> DATA_INATIVOU_TIPO_CONTRATO_COTADA { get; set; }
        public Nullable<int> ID_USUARIO_INATIVOU { get; set; }
    
        public virtual ICollection<tipo_contrato_empresa_usuario_cotada> tipo_contrato_empresa_usuario_cotada { get; set; }
    }
}
