//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteMercado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo_contrato_empresa_usuario_cotada
    {
        public tipo_contrato_empresa_usuario_cotada()
        {
            this.financeiro_cobranca_faturamento = new HashSet<financeiro_cobranca_faturamento>();
        }
    
        public int ID_TIPO_CONTRATO_EMPRESA_USUARIO_COTADA { get; set; }
        public int ID_CODIGO_EMPRESA_USUARIO { get; set; }
        public int ID_CODIGO_TIPO_CONTRATO_COTADA { get; set; }
    
        public virtual empresa_usuario empresa_usuario { get; set; }
        public virtual ICollection<financeiro_cobranca_faturamento> financeiro_cobranca_faturamento { get; set; }
        public virtual tipos_contrato tipos_contrato { get; set; }
    }
}
