//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteMercado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class unidades_produto
    {
        public unidades_produto()
        {
            this.itens_cotacao = new HashSet<itens_cotacao>();
            this.produtoes = new HashSet<produto>();
        }
    
        public int ID_CODIGO_UNIDADE_PRODUTO { get; set; }
        public string DESCRICAO_UNIDADE_PRODUTO { get; set; }
    
        public virtual ICollection<itens_cotacao> itens_cotacao { get; set; }
        public virtual ICollection<produto> produtoes { get; set; }
    }
}
