//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteMercado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario_modulo_historico_empresas
    {
        public int ID_CODIGO_HISTORICO_MODULO_USUARIO_EMPRESAS { get; set; }
        public int ID_HISTORICO_USUARIO_EMPRESAS { get; set; }
        public int ID_CODIGO_MODULO { get; set; }
    
        public virtual modulo modulo { get; set; }
        public virtual usuario_historico_empresas usuario_historico_empresas { get; set; }
    }
}
