//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteMercado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario_modulo
    {
        public int ID_CODIGO_USUARIO_MODULO { get; set; }
        public int ID_CODIGO_MODULO { get; set; }
        public int ID_CODIGO_EMPRESA_USUARIO { get; set; }
        public System.DateTime DATA_LIMITE_USO_MODULO { get; set; }
        public System.DateTime DATA_ATIVOU_MODULO { get; set; }
        public bool MODULO_ATIVO_USUARIO { get; set; }
        public Nullable<System.DateTime> DATA_INATIVOU_MODULO { get; set; }
        public Nullable<int> ID_EMPRESA_USUARIO_USUARIO_INATIVOU_MODULO { get; set; }
        public bool MODULO_PAGO { get; set; }
    
        public virtual empresa_usuario empresa_usuario { get; set; }
        public virtual modulo modulo { get; set; }
    }
}
